### ISSUE TITLE
Ideas for visualisations

### ISSUE THREAD

**Issue by mcelearr** [gabrielperales/formulationTool#10]
Put your good ideas for visualisations in here. Let's choose by the end of the day and go with that.

**Comment by mcelearr** [comment]
https://gist.github.com/jdarling/2073ba4c2d640236e2e2 I got this working but it doesn't look great and the in-built functions are kind of weird...

**Comment by mcelearr** [comment]
http://sigmajs.org/

This looks like a promising one! Uses Web GL as well ;)

**Comment by mcelearr** [comment]
https://www.mindmup.com

This is the one I found yesterday. It seems to conform to the mindmap pattern the best of any of the libraries I've seen

**Comment by cnludlow** [comment]
The Sigmajs one looks really cool. It has a good layout and it looks modern/professional. I guess I like the neural net look.

**Comment by mcelearr** [comment]
I think we're going to go with sigmajs
