### ISSUE TITLE
Colour scheme for the app

### ISSUE THREAD

**Issue by mcelearr** [gabrielperales/formulationTool#12]
Background - F4F4FA
Primary - 6D72C2
Secondary - A58E35
Others - 353CA5, 58490B

**Comment by mcelearr** [comment]
Okay this colour scheme kind of sucks. Let's think of a way of coming up with a better one.

**Comment by TroyMaeder** [comment]
Sounds good, let's decide on something before the end of the day.

**Comment by mcelearr** [comment]
@TroyMaeder Would you like to pick this up? I'm happy to do it because it's something I need to practice. Maybe grab noga/heather/sofia for a few ticks to run the ideas by them.

**Comment by TroyMaeder** [comment]
I believe Anneka is taking charge of that one now : )

**Comment by AnnekaSillitoe** [comment]
CSS hex's for colour scheme:
.color-background: { color: #ffffff }
.color-primary-0 { color: #5F97A2 }
.color-primary-1 { color: #9B9B9B }
.color-primary-2 { color: #AAB8BB }
.color-primary-3 { color: #2E8898 }
.color-primary-4 { color: #037C93 }

**Comment by AnnekaSillitoe** [comment]
Fonts:
<link href="https://fonts.googleapis.com/css?family=Raleway:100,200,300,400,500,600,700|Source+Sans+Pro:200,300,400,600,700" rel="stylesheet">
font-family: 'Raleway', sans-serif;
font-family: 'Source Sans Pro', sans-serif;

This gives us multiple options to work with one sizes, we can cut this down if we find we don't need as many.

**Comment by mcelearr** [comment]
Done and saved in SASS
