### ISSUE TITLE
Standup 11am 14/09 Agenda

### ISSUE THREAD

**Issue by mcelearr** [gabrielperales/formulationTool#15]
- Progress from yesterday
  We researched different ways of visualising the patient data. Sigma.js was chosen as the visualisation tool. To manage users and login, we are using a framework called NG Admin which creates a admin GUI using Angular.
- NG Admin
  Because we have chosen NG Admin as a means for the clinicians to interact with the data, this controls the data structures that we use and how the clinicians can add/update/delete data. **Gabriel** will explain the following data structures, why we have chosen them, and how he plans to have clinicians alter them:
  - Clinician
  - Client
  - Nodes
  - Edges
- Test login
  **Gabriel** could you set up a test email and password for us to use the app? I know you set that up for Chris.
- Quickstart guide
  Because we're trusting ngadmin to be tested already, we're not going to do any testing in this 4 day sprint per se. Because of the that, the only test we will be doing to merge pull requests is a visual one. **Gabriel**, could me and Troy have a quickstart guide in the readme so we can run NG Admin?
- Design work
  We don't have a clear design, logo etc. laid out as yet. Would anyone like to pick this up? I can do it if needs be.
- Wireframes
  Because we're using NG Admin to enter all the data, that changes the way we wireframe. We have to remember that there will be a navigation bar on the side at all times.

**Comment by cnludlow** [comment]
Thanks for all of your work. I can pop by Bethnal Green tomorrow (Thursday) if you want my feedback?

**Comment by mcelearr** [comment]
Oh that would be great. I'd actually like you to see something today. Can you come in on Thursday morning?

**Comment by cnludlow** [comment]
Yes, Thursday morning works well. **9am, 10am, or 11am**? Whatever works best. Alternatively, if you need me there today I could try making it for around 4pm?

**Comment by cnludlow** [comment]
Just some examples of formulations with the 'symptom' represented in red and causal factors in blue (there are no treatment nodes in these examples). 

![screen shot 2016-09-14 at 12 20 14 pm](https://cloud.githubusercontent.com/assets/22154174/18510562/a0456856-7a76-11e6-9e35-064bf1695840.png)
![screen shot 2016-09-14 at 12 21 34 pm](https://cloud.githubusercontent.com/assets/22154174/18510563/a06700d8-7a76-11e6-919e-eaeb8e91b0dd.png)

**Comment by mcelearr** [comment]
Hello @cnludlow. Could you please come in at 11am tomorrow? We are at 14 Palmers Road, London, E2 0SY.

**Comment by mcelearr** [comment]
My contact number is 07725047200. Give me a call if you have any issues getting here.

**Comment by cnludlow** [comment]
Sure thing @mcelearr. See you guys at 11am. Thanks for all the effort you have all been putting in.
