### ISSUE TITLE
Move into AFC organisation repo

### ISSUE THREAD

**Issue by MHemsley** [gabrielperales/formulationTool#44]
Organization link - https://github.com/CYPIAPT-LNDSE

**Comment by gabrielperales** [comment]
@MHemsley we don't have privileges to do it, as we are not part of that organization. You can fork our repo or give us rights to do it.

**Comment by CYPIAPT-admin** [comment]
@gabrielperales Rights given to you

**Comment by mcelearr** [comment]
Done
