### ISSUE TITLE
Message 

### ISSUE THREAD

**Issue by cnludlow** [gabrielperales/formulationTool#9]
I will keep an eye on this project/website today. Please message me if you need to discuss the project. Chris

**Comment by mcelearr** [comment]
Okay brilliant. Thanks a lot Chris. We will we be in touch with you if we have any questions.

**Comment by gabrielperales** [comment]
@cnludlow we are setting up a development environment to deploy our platform. You can check it out in https://formulate.herokuapp.com . I'm going to email to you a username and a password to start trying it.

**Comment by gabrielperales** [comment]
@cnludlow I have deployed our current version on https://formulate.herokuapp.com . Check it out :)
